extra:
  homepage: https://vocabwise.github.io/
  tags:
    CSS: css
    HTML5: html
    JavaScript: js

extra_css:

- https://qihang-zhang.github.io/customized_mkdocs/stylesheets/extra.css

extra_javascript:

- https://polyfill.io/v3/polyfill.min.js?features=es6

- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:

- attr_list

- pymdownx.arithmatex:
    generic: true

- toc:
    permalink: true
    toc_depth: 4

- pymdownx.superfences

- pymdownx.highlight

- footnotes

plugins:

- search

- bibtex:
    bib_file: docs/assets/references.bib

- blog:
    authors_file: '{blog}/.authors.yml'
    blog_dir: blog
    blog_toc: true
    draft: true
    draft_if_future_date: false
    draft_on_serve: true
    post_date_format: medium
    post_dir: '{blog}/Posts/published'
    post_url_date_format: yyyy/MM/dd
    post_url_format: '{date}/{slug}'

- meta

- tags

- info:
    archive: false
    archive_stop_on_violation: false
    enabled: false
    enabled_on_serve: true

- offline

repo_name: VocabWise/blogs

repo_url: https://github.com/VocabWise/blogs

site_name: VocabWise's Blog

site_url: https://vocabwise.github.io/blogs

theme:
  features:
  - katex
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.path
  - search.suggest
  - search.highlight
  - search.share
  - header.autohide
  - navigation.footer
  - toc.integrate
  - navigation.sections
  - content.code.copy
  icon:
    next: fontawesome/solid/angle-right
    previous: fontawesome/solid/angle-left
    repo: fontawesome/brands/git-alt
    tag:
      css: fontawesome/brands/css3
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
  language: en
  name: material
  palette:
  - accent: light blue
    primary: white
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - accent: light blue
    primary: black
    scheme: slate
    toggle:
      icon: material/brightness-3
      name: Switch to light mode
nav: 
  - blog: 
    - index: blog/index.md
  - index.md
