authors:
  <qihang>:
    name: Qihang        # Author name
    description: Learning By Doing.
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4
    slug: qihang
    url: https://qihang-zhang.com
    

  <jossie>:
    name: Jossie
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/88167742?v=4
  
  <felix>:
    name: Felix
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/51791082?v=4