authors:
  <qihang>:
    name: Qihang        # Author name
    description: NaN # Author description
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4         # Author avatar

  <Jossie>:
    name: Jossie
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4
  
  <Felix>:
    name: Felix
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4