authors:
  <qihang>:
    name: Qihang        # Author name
    description: A LLM Explorer.
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4
    

  <jossie>:
    name: Jossie
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/88167742?v=4
  
  <felix>:
    name: Felix
    description: NaN
    avatar: https://avatars.githubusercontent.com/u/51791082?v=4