# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:  # manual trigger
  pull_request:
    branches: [main]
    types: [closed]   # PR closed trigger

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout edge repo
      - name: Checkout Edge Repo (self)
        uses: actions/checkout@v4

      - name: install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH      

      - name: release the blog
        run: |
          uv run 